server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/votronghung_2280601119?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Tronghung021204@

spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=50MB

# OAuth2 Google
